<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CpuSeeder extends Seeder
{
    public function run(): void
    {
        $category = Category::where('slug', 'main-cpu-vga')->first()
            ?? Category::firstOrCreate(
                ['slug' => 'main-cpu-vga'],
                ['name' => 'Main, CPU, VGA', 'description' => 'Linh kiện cốt lõi: Bo mạch chủ, Vi xử lý, Card màn hình']
            );

        $cpus = [
            // ==================== INTEL (25 sản phẩm) ====================
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core Ultra 9 285K (Up to 5.7GHz, 24 Nhân 24 Luồng, 36MB Cache, LGA 1851)',
                'sku' => 'INTEL-ULTRA9-285K',
                'price' => 15990000,
                'stock' => 15,
                'description' => 'Intel Core Ultra 9 285K thế hệ Arrow Lake mới nhất cho socket LGA 1851, trang bị 24 nhân (8 P-core + 16 E-core), tiến trình 3nm, tích hợp NPU xử lý AI hiệu năng cao.',
                'specs' => [
                    'Socket' => 'LGA 1851',
                    'Số nhân / Luồng' => '24 Nhân / 24 Luồng (8 P-cores, 16 E-cores)',
                    'Xung nhịp tối đa' => 'Up to 5.7 GHz',
                    'Bộ nhớ đệm (Cache)' => '36MB Intel Smart Cache + 40MB L2',
                    'TDP' => '125W (Maximum Turbo Power 250W)',
                    'Đồ họa tích hợp' => 'Intel Graphics (4 Xe Cores)',
                    'Hỗ trợ RAM' => 'DDR5-6400 up to 192GB',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core Ultra 7 265K (Up to 5.5GHz, 20 Nhân 20 Luồng, 30MB Cache, LGA 1851)',
                'sku' => 'INTEL-ULTRA7-265K',
                'price' => 11490000,
                'stock' => 20,
                'description' => 'Vi xử lý thế hệ Intel Core Ultra 7 265K kiến trúc Arrow Lake 20 nhân (8 P-Core + 12 E-Core), tối ưu hóa hiệu năng render, gaming và tác vụ AI đột phá.',
                'specs' => [
                    'Socket' => 'LGA 1851',
                    'Số nhân / Luồng' => '20 Nhân / 20 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.5 GHz',
                    'Bộ nhớ đệm (Cache)' => '30MB Intel Smart Cache',
                    'TDP' => '125W (Maximum Turbo 250W)',
                    'Đồ họa tích hợp' => 'Intel Graphics (4 Xe Cores)',
                    'Hỗ trợ RAM' => 'DDR5-6400',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core Ultra 7 265KF (Up to 5.5GHz, 20 Nhân 20 Luồng, 30MB Cache, LGA 1851, No iGPU)',
                'sku' => 'INTEL-ULTRA7-265KF',
                'price' => 10990000,
                'stock' => 18,
                'description' => 'Intel Core Ultra 7 265KF phiên bản không tích hợp iGPU, giá thành tối ưu cho streamer và gamer sở hữu card đồ họa rời high-end.',
                'specs' => [
                    'Socket' => 'LGA 1851',
                    'Số nhân / Luồng' => '20 Nhân / 20 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.5 GHz',
                    'Bộ nhớ đệm (Cache)' => '30MB Intel Smart Cache',
                    'TDP' => '125W',
                    'Đồ họa tích hợp' => 'Không có (Cần Card VGA rời)',
                    'Hỗ trợ RAM' => 'DDR5-6400',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core Ultra 5 245K (Up to 5.2GHz, 14 Nhân 14 Luồng, 24MB Cache, LGA 1851)',
                'sku' => 'INTEL-ULTRA5-245K',
                'price' => 8490000,
                'stock' => 25,
                'description' => 'Intel Core Ultra 5 245K là mẫu CPU tầm trung cao cấp với 14 nhân (6 P-core + 8 E-core), khả năng ép xung Unlocked trên bo mạch chủ Z890.',
                'specs' => [
                    'Socket' => 'LGA 1851',
                    'Số nhân / Luồng' => '14 Nhân / 14 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.2 GHz',
                    'Bộ nhớ đệm (Cache)' => '24MB Intel Smart Cache',
                    'TDP' => '125W',
                    'Đồ họa tích hợp' => 'Intel Graphics',
                    'Hỗ trợ RAM' => 'DDR5-6400',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core Ultra 5 245KF (Up to 5.2GHz, 14 Nhân 14 Luồng, 24MB Cache, LGA 1851, No iGPU)',
                'sku' => 'INTEL-ULTRA5-245KF',
                'price' => 7990000,
                'stock' => 30,
                'description' => 'Intel Core Ultra 5 245KF tối ưu chi phí cho dàn PC Gaming tầm trung - cao cấp thế hệ mới socket LGA 1851.',
                'specs' => [
                    'Socket' => 'LGA 1851',
                    'Số nhân / Luồng' => '14 Nhân / 14 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.2 GHz',
                    'Bộ nhớ đệm (Cache)' => '24MB Intel Smart Cache',
                    'TDP' => '125W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR5-6400',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i9-14900KS (Up to 6.2GHz, 24 Nhân 32 Luồng, 36MB Cache, LGA 1700)',
                'sku' => 'INTEL-I9-14900KS',
                'price' => 17990000,
                'stock' => 8,
                'description' => 'Phiên bản đặc biệt Intel Core i9-14900KS đạt xung nhịp kỷ lục 6.2GHz ngay từ khi mở hộp, vua hiệu năng Gaming và Đồ họa chuyên nghiệp.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '24 Nhân / 32 Luồng (8 P-Core + 16 E-Core)',
                    'Xung nhịp tối đa' => 'Up to 6.2 GHz',
                    'Bộ nhớ đệm (Cache)' => '36MB Intel Smart Cache',
                    'TDP' => '150W (Max Turbo 253W+)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i9-14900K (Up to 6.0GHz, 24 Nhân 32 Luồng, 36MB Cache, LGA 1700)',
                'sku' => 'INTEL-I9-14900K',
                'price' => 15290000,
                'stock' => 18,
                'description' => 'CPU flagship Raptor Lake Refresh i9-14900K với 24 nhân 32 luồng, xung nhịp Boost 6.0GHz phục vụ hoàn hảo các ứng dụng 3D, dựng phim và chơi game 4K.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '24 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 6.0 GHz',
                    'Bộ nhớ đệm (Cache)' => '36MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 253W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4-3200 / DDR5-5600',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i9-14900KF (Up to 6.0GHz, 24 Nhân 32 Luồng, 36MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I9-14900KF',
                'price' => 14590000,
                'stock' => 20,
                'description' => 'Intel Core i9-14900KF sức mạnh đỉnh cao 24 nhân 32 luồng 6.0GHz cắt bỏ đồ họa tích hợp giúp tiết kiệm chi phí cho dàn máy chiến game đỉnh cao.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '24 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 6.0 GHz',
                    'Bộ nhớ đệm (Cache)' => '36MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 253W)',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i9-14900 (Up to 5.8GHz, 24 Nhân 32 Luồng, 36MB Cache, LGA 1700)',
                'sku' => 'INTEL-I9-14900',
                'price' => 13990000,
                'stock' => 12,
                'description' => 'Intel Core i9-14900 phiên bản tiêu chuẩn TDP 65W tiết kiệm điện năng năng lượng cao, giữ trọn 24 nhân 32 luồng mạnh mẽ.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '24 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.8 GHz',
                    'Bộ nhớ đệm (Cache)' => '36MB Intel Smart Cache',
                    'TDP' => '65W (Max Turbo 219W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i7-14700K (Up to 5.6GHz, 20 Nhân 28 Luồng, 33MB Cache, LGA 1700)',
                'sku' => 'INTEL-I7-14700K',
                'price' => 10890000,
                'stock' => 35,
                'description' => 'Intel Core i7-14700K nâng cấp đáng giá với 20 nhân (8 P-core + 12 E-core) 28 luồng, dòng CPU quốc dân cho Creator và Gamer chuyên nghiệp.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '20 Nhân / 28 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '33MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 253W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i7-14700KF (Up to 5.6GHz, 20 Nhân 28 Luồng, 33MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I7-14700KF',
                'price' => 10290000,
                'stock' => 30,
                'description' => 'CPU Intel Core i7-14700KF 20 nhân 28 luồng unlocked ép xung, sự lựa chọn số 1 cho các cấu hình máy tính gaming cao cấp.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '20 Nhân / 28 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '33MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 253W)',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i7-14700 (Up to 5.4GHz, 20 Nhân 28 Luồng, 33MB Cache, LGA 1700)',
                'sku' => 'INTEL-I7-14700',
                'price' => 9690000,
                'stock' => 22,
                'description' => 'Core i7-14700 không đuôi K hoạt động mát mẻ, 20 nhân 28 luồng xử lý đa nhiệm tác vụ đồ họa và game siêu mượt.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '20 Nhân / 28 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.4 GHz',
                    'Bộ nhớ đệm (Cache)' => '33MB Intel Smart Cache',
                    'TDP' => '65W (Max Turbo 219W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i7-14700F (Up to 5.4GHz, 20 Nhân 28 Luồng, 33MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I7-14700F',
                'price' => 9190000,
                'stock' => 25,
                'description' => 'Intel Core i7-14700F phiên bản tiêu chuẩn không có nhân đồ họa, giá thành dễ tiếp cận cho cấu hình PC hiệu năng cao.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '20 Nhân / 28 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.4 GHz',
                    'Bộ nhớ đệm (Cache)' => '33MB Intel Smart Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-14600K (Up to 5.3GHz, 14 Nhân 20 Luồng, 24MB Cache, LGA 1700)',
                'sku' => 'INTEL-I5-14600K',
                'price' => 7690000,
                'stock' => 40,
                'description' => 'Intel Core i5-14600K là ngôi vương CPU Gaming tầm trung với 14 nhân (6 P-core + 8 E-core), khả năng ép xung xuất sắc.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '14 Nhân / 20 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.3 GHz',
                    'Bộ nhớ đệm (Cache)' => '24MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 181W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-14600KF (Up to 5.3GHz, 14 Nhân 20 Luồng, 24MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I5-14600KF',
                'price' => 7190000,
                'stock' => 45,
                'description' => 'Intel Core i5-14600KF không iGPU, sự lựa chọn tối ưu ngân sách số 1 cho game thủ xây dựng dàn PC gaming cùng RTX 4060 / 4070.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '14 Nhân / 20 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.3 GHz',
                    'Bộ nhớ đệm (Cache)' => '24MB Intel Smart Cache',
                    'TDP' => '125W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-14500 (Up to 5.0GHz, 14 Nhân 20 Luồng, 24MB Cache, LGA 1700)',
                'sku' => 'INTEL-I5-14500',
                'price' => 6290000,
                'stock' => 25,
                'description' => 'Core i5-14500 sở hữu 14 nhân 20 luồng cực mạnh cho nhu cầu làm việc văn phòng nâng cao, thiết kế đồ họa 2D/3D và chơi game.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '14 Nhân / 20 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.0 GHz',
                    'Bộ nhớ đệm (Cache)' => '24MB Intel Smart Cache',
                    'TDP' => '65W (Max Turbo 154W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-14400 (Up to 4.7GHz, 10 Nhân 16 Luồng, 20MB Cache, LGA 1700)',
                'sku' => 'INTEL-I5-14400',
                'price' => 5490000,
                'stock' => 30,
                'description' => 'Intel Core i5-14400 10 nhân (6 P-core + 4 E-core) 16 luồng, CPU phổ thông được ưa chuộng nhất dành cho mọi nhà.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '10 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.7 GHz',
                    'Bộ nhớ đệm (Cache)' => '20MB Intel Smart Cache',
                    'TDP' => '65W (Max Turbo 148W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 730',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-14400F (Up to 4.7GHz, 10 Nhân 16 Luồng, 20MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I5-14400F',
                'price' => 4890000,
                'stock' => 50,
                'description' => 'Intel Core i5-14400F CPU gaming quốc dân phân khúc phổ thông 10 nhân 16 luồng, giá hợp lý hiệu năng vượt trội.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '10 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.7 GHz',
                    'Bộ nhớ đệm (Cache)' => '20MB Intel Smart Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i3-14100 (Up to 4.7GHz, 4 Nhân 8 Luồng, 12MB Cache, LGA 1700)',
                'sku' => 'INTEL-I3-14100',
                'price' => 3490000,
                'stock' => 20,
                'description' => 'Intel Core i3-14100 4 nhân 8 luồng xung nhịp 4.7GHz đáp ứng mượt mà nhu cầu học tập, làm việc văn phòng và giải trí gia đình.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '4 Nhân / 8 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.7 GHz',
                    'Bộ nhớ đệm (Cache)' => '12MB Intel Smart Cache',
                    'TDP' => '60W',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 730',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i3-14100F (Up to 4.7GHz, 4 Nhân 8 Luồng, 12MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I3-14100F',
                'price' => 2890000,
                'stock' => 40,
                'description' => 'Intel Core i3-14100F CPU giá rẻ ngon nhất cho cấu hình PC Gaming nhập môn kết hợp GTX 1650 / RTX 3050.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '4 Nhân / 8 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.7 GHz',
                    'Bộ nhớ đệm (Cache)' => '12MB Intel Smart Cache',
                    'TDP' => '58W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i9-13900K (Up to 5.8GHz, 24 Nhân 32 Luồng, 36MB Cache, LGA 1700)',
                'sku' => 'INTEL-I9-13900K',
                'price' => 13590000,
                'stock' => 10,
                'description' => 'Intel Core i9-13900K thế hệ 13 Raptor Lake 24 nhân 32 luồng siêu khỏe cho máy trạm làm đồ họa và giả lập nặng.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '24 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.8 GHz',
                    'Bộ nhớ đệm (Cache)' => '36MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 253W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i7-13700K (Up to 5.4GHz, 16 Nhân 24 Luồng, 30MB Cache, LGA 1700)',
                'sku' => 'INTEL-I7-13700K',
                'price' => 9290000,
                'stock' => 15,
                'description' => 'Intel Core i7-13700K 16 nhân (8 P-core + 8 E-core) 24 luồng, hiệu năng cao bền bỉ cho dựng phim 4K và Stream.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '16 Nhân / 24 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.4 GHz',
                    'Bộ nhớ đệm (Cache)' => '30MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 253W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-13600K (Up to 5.1GHz, 14 Nhân 20 Luồng, 24MB Cache, LGA 1700)',
                'sku' => 'INTEL-I5-13600K',
                'price' => 6890000,
                'stock' => 20,
                'description' => 'Intel Core i5-13600K mẫu CPU huyền thoại thế hệ 13 được đánh giá cao nhất về hiệu năng trên giá thành.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '14 Nhân / 20 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.1 GHz',
                    'Bộ nhớ đệm (Cache)' => '24MB Intel Smart Cache',
                    'TDP' => '125W (Max Turbo 181W)',
                    'Đồ họa tích hợp' => 'Intel UHD Graphics 770',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-13400F (Up to 4.6GHz, 10 Nhân 16 Luồng, 20MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I5-13400F',
                'price' => 4290000,
                'stock' => 35,
                'description' => 'Intel Core i5-13400F 10 nhân 16 luồng cân cực tốt mọi dòng card đồ họa tầm trung như RTX 3060, RTX 4060.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '10 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '20MB Intel Smart Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'Intel',
                'name' => 'Vi xử lý Intel Core i5-12400F (Up to 4.4GHz, 6 Nhân 12 Luồng, 18MB Cache, LGA 1700, No iGPU)',
                'sku' => 'INTEL-I5-12400F',
                'price' => 2890000,
                'stock' => 60,
                'description' => 'Intel Core i5-12400F CPU 6 nhân 12 luồng giá rẻ ổn định bền bỉ vượt thời gian, chạy mát mẻ thích hợp mọi cấu hình.',
                'specs' => [
                    'Socket' => 'LGA 1700',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.4 GHz',
                    'Bộ nhớ đệm (Cache)' => '18MB Intel Smart Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4 / DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],

            // ==================== AMD (25 sản phẩm) ====================
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 9950X (Up to 5.7GHz, 16 Nhân 32 Luồng, 80MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN9-9950X',
                'price' => 16490000,
                'stock' => 12,
                'description' => 'AMD Ryzen 9 9950X kiến trúc Zen 5 tiến trình 4nm mới nhất, 16 nhân 32 luồng đỉnh cao cho Workstation, 3D Rendering và AI.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '16 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.7 GHz (Base 4.3GHz)',
                    'Bộ nhớ đệm (Cache)' => '80MB (L2+L3 Cache)',
                    'TDP' => '170W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics (2 Cores)',
                    'Hỗ trợ RAM' => 'DDR5-5600 Dual Channel',
                ],
                'image' => 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 9900X (Up to 5.6GHz, 12 Nhân 24 Luồng, 76MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN9-9900X',
                'price' => 12990000,
                'stock' => 15,
                'description' => 'AMD Ryzen 9 9900X Zen 5 trang bị 12 nhân 24 luồng mạnh mẽ, xử lý mượt mà tác vụ đồ họa chuyên sâu và lập trình ứng dụng.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '12 Nhân / 24 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.6 GHz (Base 4.4GHz)',
                    'Bộ nhớ đệm (Cache)' => '76MB Cache',
                    'TDP' => '120W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 9700X (Up to 5.5GHz, 8 Nhân 16 Luồng, 40MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN7-9700X',
                'price' => 9490000,
                'stock' => 25,
                'description' => 'AMD Ryzen 7 9700X thế hệ Zen 5 8 nhân 16 luồng tiêu thụ điện năng tối ưu chỉ 65W TDP nhưng mang lại sức mạnh đơn nhân áp đảo.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.5 GHz (Base 3.8GHz)',
                    'Bộ nhớ đệm (Cache)' => '40MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 9600X (Up to 5.4GHz, 6 Nhân 12 Luồng, 38MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN5-9600X',
                'price' => 7190000,
                'stock' => 30,
                'description' => 'AMD Ryzen 5 9600X CPU gaming Zen 5 tối ưu nhất phân khúc tầm trung với 6 nhân 12 luồng xung nhịp boost 5.4GHz.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.4 GHz (Base 3.9GHz)',
                    'Bộ nhớ đệm (Cache)' => '38MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 9800X3D (Up to 5.2GHz, 8 Nhân 16 Luồng, 104MB Cache 3D V-Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN7-9800X3D',
                'price' => 13990000,
                'stock' => 20,
                'description' => 'AMD Ryzen 7 9800X3D vương miệng CPU Gaming nhanh nhất thế giới thế hệ 2nd Gen 3D V-Cache, 104MB cache cực khủng cho FPS gaming kỷ lục.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.2 GHz (Base 4.7GHz)',
                    'Bộ nhớ đệm (Cache)' => '104MB (L2+L3 3D V-Cache)',
                    'TDP' => '120W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5 EXPO',
                ],
                'image' => 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 7800X3D (Up to 5.0GHz, 8 Nhân 16 Luồng, 104MB Cache 3D V-Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN7-7800X3D',
                'price' => 11290000,
                'stock' => 25,
                'description' => 'AMD Ryzen 7 7800X3D huyền thoại gaming thế hệ Zen 4 3D V-Cache, được hàng triệu game thủ Esport và AAA yêu thích.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.0 GHz',
                    'Bộ nhớ đệm (Cache)' => '104MB 3D V-Cache',
                    'TDP' => '120W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 7950X3D (Up to 5.7GHz, 16 Nhân 32 Luồng, 144MB Cache 3D V-Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN9-7950X3D',
                'price' => 16990000,
                'stock' => 10,
                'description' => 'AMD Ryzen 9 7950X3D đỉnh cao vừa chơi game đỉnh vừa làm việc render 3D nặng nhờ 16 nhân 32 luồng và 144MB 3D V-Cache.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '16 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.7 GHz',
                    'Bộ nhớ đệm (Cache)' => '144MB 3D V-Cache',
                    'TDP' => '120W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 7900X3D (Up to 5.6GHz, 12 Nhân 24 Luồng, 140MB Cache 3D V-Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN9-7900X3D',
                'price' => 12490000,
                'stock' => 14,
                'description' => 'AMD Ryzen 9 7900X3D sở hữu 12 nhân 24 luồng kèm công nghệ bộ nhớ đệm xếp chồng 3D V-Cache 140MB bứt phá trải nghiệm.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '12 Nhân / 24 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '140MB 3D V-Cache',
                    'TDP' => '120W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 7950X (Up to 5.7GHz, 16 Nhân 32 Luồng, 80MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN9-7950X',
                'price' => 14890000,
                'stock' => 15,
                'description' => 'AMD Ryzen 9 7950X 16 nhân 32 luồng Zen 4 chuyên biệt cho creator, lập trình viên và đồ họa kiến trúc chuyên nghiệp.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '16 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.7 GHz',
                    'Bộ nhớ đệm (Cache)' => '80MB Cache',
                    'TDP' => '170W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 7900X (Up to 5.6GHz, 12 Nhân 24 Luồng, 76MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN9-7900X',
                'price' => 10890000,
                'stock' => 18,
                'description' => 'AMD Ryzen 9 7900X 12 nhân 24 luồng socket AM5 mang tới hiệu năng xử lý đa luồng ấn tượng.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '12 Nhân / 24 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '76MB Cache',
                    'TDP' => '170W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 7700X (Up to 5.4GHz, 8 Nhân 16 Luồng, 40MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN7-7700X',
                'price' => 7890000,
                'stock' => 30,
                'description' => 'AMD Ryzen 7 7700X 8 nhân 16 luồng kiến trúc Zen 4 mang đến tốc độ xử lý đỉnh cao cho dàn PC Gaming hiện đại.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.4 GHz',
                    'Bộ nhớ đệm (Cache)' => '40MB Cache',
                    'TDP' => '105W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 7700 (Up to 5.3GHz, 8 Nhân 16 Luồng, 40MB Cache, Socket AM5, Kèm tản Wraith Prism)',
                'sku' => 'AMD-RYZEN7-7700',
                'price' => 7190000,
                'stock' => 20,
                'description' => 'AMD Ryzen 7 7700 tiết kiệm điện 65W TDP đi kèm tản nhiệt RGB Wraith Prism chính hãng vô cùng đẹp mắt.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.3 GHz',
                    'Bộ nhớ đệm (Cache)' => '40MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Phụ kiện đi kèm' => 'Tản nhiệt Wraith Prism RGB',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 7600X (Up to 5.3GHz, 6 Nhân 12 Luồng, 38MB Cache, Socket AM5)',
                'sku' => 'AMD-RYZEN5-7600X',
                'price' => 5490000,
                'stock' => 35,
                'description' => 'AMD Ryzen 5 7600X dòng CPU 6 nhân AM5 quốc dân giá tốt cho trải nghiệm nền tảng RAM DDR5 và PCIe 5.0.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.3 GHz',
                    'Bộ nhớ đệm (Cache)' => '38MB Cache',
                    'TDP' => '105W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 7600 (Up to 5.1GHz, 6 Nhân 12 Luồng, 38MB Cache, Socket AM5, Kèm tản Wraith Stealth)',
                'sku' => 'AMD-RYZEN5-7600',
                'price' => 4890000,
                'stock' => 40,
                'description' => 'AMD Ryzen 5 7600 hoạt động mát mẻ đi kèm quạt tản Wraith Stealth tiện lợi cho cấu hình máy tính gaming tối ưu chi phí.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.1 GHz',
                    'Bộ nhớ đệm (Cache)' => '38MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics',
                    'Phụ kiện đi kèm' => 'Tản nhiệt Wraith Stealth',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 7500F (Up to 5.0GHz, 6 Nhân 12 Luồng, 38MB Cache, Socket AM5, No iGPU)',
                'sku' => 'AMD-RYZEN5-7500F',
                'price' => 3890000,
                'stock' => 50,
                'description' => 'AMD Ryzen 5 7500F CPU AM5 không tích hợp đồ họa, P/P (Performance/Price) bá đạo nhất cho game thủ build PC AM5 giá rẻ.',
                'specs' => [
                    'Socket' => 'Socket AM5',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 5.0 GHz',
                    'Bộ nhớ đệm (Cache)' => '38MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR5',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 5700X3D (Up to 4.1GHz, 8 Nhân 16 Luồng, 100MB Cache 3D V-Cache, Socket AM4)',
                'sku' => 'AMD-RYZEN7-5700X3D',
                'price' => 6190000,
                'stock' => 25,
                'description' => 'AMD Ryzen 7 5700X3D cú hích nâng cấp hoàn hảo nhất cho người dùng đang sở hữu bo mạch chủ Socket AM4 (B450/B550/X570).',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.1 GHz',
                    'Bộ nhớ đệm (Cache)' => '100MB 3D V-Cache',
                    'TDP' => '105W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 5800X3D (Up to 4.5GHz, 8 Nhân 16 Luồng, 100MB Cache 3D V-Cache, Socket AM4)',
                'sku' => 'AMD-RYZEN7-5800X3D',
                'price' => 7490000,
                'stock' => 15,
                'description' => 'AMD Ryzen 7 5800X3D CPU 3D V-Cache đầu tiên trên thế giới mở ra kỉ nguyên đột phá FPS cho các tựa game Esport và AAA.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.5 GHz',
                    'Bộ nhớ đệm (Cache)' => '100MB 3D V-Cache',
                    'TDP' => '105W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 5950X (Up to 4.9GHz, 16 Nhân 32 Luồng, 72MB Cache, Socket AM4)',
                'sku' => 'AMD-RYZEN9-5950X',
                'price' => 10490000,
                'stock' => 12,
                'description' => 'AMD Ryzen 9 5950X 16 nhân 32 luồng huyền thoại socket AM4 dành cho máy trạm làm phim, thiết kế kiến trúc và máy chủ local.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '16 Nhân / 32 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.9 GHz',
                    'Bộ nhớ đệm (Cache)' => '72MB Cache',
                    'TDP' => '105W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 9 5900X (Up to 4.8GHz, 12 Nhân 24 Luồng, 70MB Cache, Socket AM4)',
                'sku' => 'AMD-RYZEN9-5900X',
                'price' => 7490000,
                'stock' => 18,
                'description' => 'AMD Ryzen 9 5900X 12 nhân 24 luồng cân ngọt ngào mọi tác vụ làm việc nặng lẫn chơi game 2K/4K trên nền tảng AM4.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '12 Nhân / 24 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.8 GHz',
                    'Bộ nhớ đệm (Cache)' => '70MB Cache',
                    'TDP' => '105W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 5700X (Up to 4.6GHz, 8 Nhân 16 Luồng, 36MB Cache, Socket AM4)',
                'sku' => 'AMD-RYZEN7-5700X',
                'price' => 4390000,
                'stock' => 35,
                'description' => 'AMD Ryzen 7 5700X 8 nhân 16 luồng cực mát chỉ 65W TDP, giá tốt nhất để trải nghiệm CPU 8 nhân đa nhiệm.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '36MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 7 5700G (Up to 4.6GHz, 8 Nhân 16 Luồng, Radeon Vega 8 Graphics, Socket AM4)',
                'sku' => 'AMD-RYZEN7-5700G',
                'price' => 4190000,
                'stock' => 20,
                'description' => 'AMD Ryzen 7 5700G tích hợp nhân đồ họa Radeon Vega 8 mạnh mẽ, giúp chiến game Esports mượt mà không cần cạc màn hình rời.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '8 Nhân / 16 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '20MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics (Vega 8)',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 5600X (Up to 4.6GHz, 6 Nhân 12 Luồng, 35MB Cache, Socket AM4)',
                'sku' => 'AMD-RYZEN5-5600X',
                'price' => 3690000,
                'stock' => 40,
                'description' => 'AMD Ryzen 5 5600X CPU gaming quốc dân phân khúc dưới 4 triệu đồng, hiệu năng vượt trội cho PC Gaming giá rẻ.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.6 GHz',
                    'Bộ nhớ đệm (Cache)' => '35MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 5600 (Up to 4.4GHz, 6 Nhân 12 Luồng, 35MB Cache, Socket AM4, Kèm tản Stealth)',
                'sku' => 'AMD-RYZEN5-5600',
                'price' => 3190000,
                'stock' => 45,
                'description' => 'AMD Ryzen 5 5600 lựa chọn cực hời 6 nhân 12 luồng đi kèm quạt tản chính hãng, đáp ứng hoàn hảo nhu cầu gaming 1080p.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.4 GHz',
                    'Bộ nhớ đệm (Cache)' => '35MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Phụ kiện đi kèm' => 'Tản nhiệt Wraith Stealth',
                ],
                'image' => 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 5600G (Up to 4.4GHz, 6 Nhân 12 Luồng, Radeon Vega 7 Graphics, Socket AM4)',
                'sku' => 'AMD-RYZEN5-5600G',
                'price' => 3090000,
                'stock' => 35,
                'description' => 'AMD Ryzen 5 5600G CPU tích hợp đồ họa quốc dân, chiến LOL, FIFA Online 4, Valorant cực mượt không cần cạc rời.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.4 GHz',
                    'Bộ nhớ đệm (Cache)' => '19MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'AMD Radeon Graphics (Vega 7)',
                    'Hỗ trợ RAM' => 'DDR4',
                ],
                'image' => 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800',
            ],
            [
                'brand' => 'AMD',
                'name' => 'Vi xử lý AMD Ryzen 5 5500 (Up to 4.2GHz, 6 Nhân 12 Luồng, 19MB Cache, Socket AM4, Kèm tản Stealth)',
                'sku' => 'AMD-RYZEN5-5500',
                'price' => 2290000,
                'stock' => 50,
                'description' => 'AMD Ryzen 5 5500 CPU 6 nhân 12 luồng giá tốt nhất thị trường, phù hợp cho học sinh sinh viên lắp máy tính giá học đường.',
                'specs' => [
                    'Socket' => 'Socket AM4',
                    'Số nhân / Luồng' => '6 Nhân / 12 Luồng',
                    'Xung nhịp tối đa' => 'Up to 4.2 GHz',
                    'Bộ nhớ đệm (Cache)' => '19MB Cache',
                    'TDP' => '65W',
                    'Đồ họa tích hợp' => 'Không có',
                    'Phụ kiện đi kèm' => 'Tản nhiệt Wraith Stealth',
                ],
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            ],
        ];

        foreach ($cpus as $cpu) {
            $slug = Str::slug($cpu['name']);

            Product::updateOrCreate(
                ['sku' => $cpu['sku']],
                [
                    'category_id' => $category->id,
                    'brand' => $cpu['brand'],
                    'name' => $cpu['name'],
                    'slug' => $slug,
                    'sku' => $cpu['sku'],
                    'description' => $cpu['description'],
                    'price' => $cpu['price'],
                    'stock_quantity' => $cpu['stock'],
                    'specs' => $cpu['specs'],
                    'images' => [$cpu['image']],
                ]
            );
        }
    }
}
