-- =============================================================================
-- Script: create_users_table_postgres.sql
-- Description: Script tạo bảng 'users' cho PostgreSQL tương thích với Laravel
-- Database: PostgreSQL (>= 12)
-- Project: PCShop-BE
-- =============================================================================

-- 1. Tạo bảng users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_unique UNIQUE (email)
);

-- 2. Đánh Index trên cột email nhằm tối ưu tốc độ truy vấn xác thực (Auth/Login)
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- 3. Tạo function và trigger tự động cập nhật 'updated_at' khi dữ liệu được sửa đổi
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

DROP TRIGGER IF EXISTS trigger_users_updated_at ON users;
CREATE TRIGGER trigger_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
